import { SiteConfig } from '@/types';

export const siteConfig: SiteConfig = {
  coupleName: 'Harsha & Rishika',
  weddingDate: 'November 26, 2025',
  venue: 'Hyderabad, Telangana',
  events: [
    {
      id: 'sangeet',
      title: 'Sangeet',
      dateTime: 'November 16, 2025 from 7 PM onwards',
      venueName: 'Ashva retreat',
      address: 'Hyderabad, TS',
      dressCode: 'Cocktail Attire',
      description:
        'Join us for an intimate welcome reception to kick off our wedding weekend.',
      mapLink: 'https://maps.app.goo.gl/qgruCTAsCezSgAyj9',
      imageUrl: '/images/events/sangeet.png',
    },
    {
      id: 'haldi',
      title: 'Haldi Ceremony',
      dateTime: 'November 24, 2025 from 7 AM onwards',
      venueName: 'Home',
      address: 'Jangareddygudem, AP',
      dressCode: 'Women: Pink , Men: Pista Green Kurta',
      description:
        'Our wedding ceremony will take place in the beautiful castle courtyard.',
      mapLink: 'https://maps.google.com/?q=17.093364,81.279088',
      imageUrl: '/images/events/haldi.png',
    },
    {
      id: 'wedding-ceremony',
      title: 'Wedding Ceremony',
      dateTime: 'November 26, 2025 at 9:21 AM',
      venueName: 'Taj Krishna Banjara Hills',
      address: 'Hyderabad, TS',
      dressCode: 'Indian Attire',
      description: 'Dinner, dancing, and celebration in the grand ballroom.',
      mapLink: 'https://maps.app.goo.gl/YPH67dWiQQSwwmJ79',
      imageUrl: '/images/events/wedding.png',
    },
    {
      id: 'reception',
      title: 'Reception',
      dateTime: 'November 30, 2025 from 7 PM onwards',
      venueName: 'Home',
      address: 'Jangareddygudem, AP',
      dressCode: 'Indo-Western',
      description: 'Dinner, dancing, and celebration in the grand ballroom.',
      mapLink: 'https://maps.google.com/?q=17.093364,81.279088',
      imageUrl: '/images/events/reception.png',
    },
    {
      id: 'pellikoduku',
      title: 'Pellikoduku',
      dateTime: 'November 23, 2025 from 9 AM onwards',
      venueName: 'Home',
      address: 'Jangareddygudem, AP',
      dressCode: 'Indian Attire Pastel Colors',
      description: 'Dinner, dancing, and celebration in the grand ballroom.',
      mapLink: 'https://maps.google.com/?q=17.093364,81.279088',
      imageUrl: '/images/events/pellikoduku.png',
    },
    {
      id: 'gajula-veduka',
      title: 'గాజుల వేడుక',
      dateTime: 'November 23, 2025 from 6 PM onwards',
      venueName: 'Home',
      address: 'Jangareddygudem, AP',
      dressCode: 'Indian Attire',
      description: 'Dinner, dancing, and celebration in the grand ballroom.',
      mapLink: 'https://maps.google.com/?q=17.093364,81.279088',
      imageUrl: '/images/events/gajulu.png',
    },
    {
      id: 'mehandi',
      title: 'Mehandi',
      dateTime: 'November 24, 2025 from 6 PM onwards',
      venueName: 'Home',
      address: 'Jangareddygudem, AP',
      dressCode: 'Kalankari Pattern',
      description: 'Dinner, dancing, and celebration in the grand ballroom.',
      mapLink: 'https://maps.google.com/?q=17.093364,81.279088',
      imageUrl: '/images/events/mehandi.png',
    },
    {
      id: 'pellikuthuru',
      title: 'Pellikuthuru',
      dateTime: 'November 23, 2025 from 9 AM onwards',
      venueName: 'Home',
      address: 'Hyderabad, TS',
      dressCode: 'Indian Attire Pastel Colors',
      description: 'Dinner, dancing, and celebration in the grand ballroom.',
      mapLink: 'https://maps.app.goo.gl/wvM6PzV5dousgyTS9?g_st=iw',
      imageUrl: '/images/events/pellikuthuru.png',
    },
    {
      id: 'haldi2',
      title: 'Haldi Ceremony',
      dateTime: 'November 23, 2025 from 12 PM onwards',
      venueName: 'Home',
      address: 'Hyderabad, TS',
      dressCode: 'Yellows/Rustic Orange/Pink',
      description:
        'Our wedding ceremony will take place in the beautiful castle courtyard.',
      mapLink: 'https://maps.app.goo.gl/wvM6PzV5dousgyTS9?g_st=iw',
      imageUrl: '/images/events/haldi2.png',
    },
    {
      id: 'mehandi2',
      title: 'Mehandi',
      dateTime: 'November 23, 2025 from 3 PM onwards',
      venueName: 'Home',
      address: 'Hyderabad, TS',
      dressCode: 'Pop Up Colors',
      description: 'Dinner, dancing, and celebration in the grand ballroom.',
      mapLink: 'https://maps.app.goo.gl/wvM6PzV5dousgyTS9?g_st=iw',
      imageUrl: '/images/events/mehandi.png',
    },
  ],
  storyItems: [
    {
      id: 'how-we-met',
      title: 'How We Met',
      year: '2019',
      description:
        'We first met at a coffee shop in San Francisco during a rainy afternoon.',
      imageUrl: '/images/story/met.jpg',
    },
    {
      id: 'engagement',
      title: 'The Engagement',
      year: '2024',
      description:
        'Michael proposed during a sunset hike in Big Sur with the Pacific Ocean as our backdrop.',
      imageUrl: '/images/story/engagement.jpg',
    },
    {
      id: 'favorite-adventure',
      title: 'Our Favorite Adventure',
      year: '2023',
      description:
        'Our trip to Italy where we fell in love with the country and decided to have our wedding there.',
      imageUrl: '/images/story/italy.jpg',
    },
  ],
  galleryItems: [
    {
      id: 'photography',
      title: 'Photography',
      imageUrl: '/images/gallery/photography.jpg',
      size: 'large',
    },
    {
      id: 'ceremony',
      title: 'Ceremony',
      imageUrl: '/images/gallery/ceremony.jpg',
      size: 'small',
    },
    {
      id: 'wedding-design',
      title: 'Wedding Design',
      imageUrl: '/images/gallery/design.jpg',
      size: 'small',
    },
    {
      id: 'florals',
      title: 'Florals',
      imageUrl: '/images/gallery/florals.jpg',
      size: 'large',
    },
    {
      id: 'catering',
      title: 'Catering',
      imageUrl: '/images/gallery/catering.jpg',
      size: 'small',
    },
    {
      id: 'music',
      title: 'Music',
      imageUrl: '/images/gallery/music.jpg',
      size: 'small',
    },
  ],
  testimonials: [
    {
      id: 'testimonial-1',
      text: "Dianne and Michael are the perfect couple. Their love story is truly inspiring and we can't wait to celebrate their special day.",
      author: 'Sarah & David',
      avatar: '/images/testimonials/sarah-david.jpg',
    },
    {
      id: 'testimonial-2',
      text: "We've known them for years and couldn't be happier to see them tie the knot. Their wedding will be absolutely beautiful.",
      author: 'Emily & James',
      avatar: '/images/testimonials/emily-james.jpg',
    },
    {
      id: 'testimonial-3',
      text: "Dianne and Michael's love is pure and genuine. We're so excited to be part of their journey together.",
      author: 'Lisa & Mark',
      avatar: '/images/testimonials/lisa-mark.jpg',
    },
  ],
  rsvpUrl: 'https://form.jotform.com/harshavardhan0605/rsvp-form',
  registryUrl: 'https://registry.example.com',
};
